
main:
  - hasslefree:
    product-id: 84194756
    title: Hassle-Free Hosting Service
    tag: You Won’t Lift a Finger
    feature-image: img-ser-hassle-collage.jpg
    thumb-image: img-ser-hassle-thumb.jpg
    link: service-hassle-free.html
    excerpt: 
    - Our Spotless Cleaning Service before AND after your guests come and go. We bring OUR OWN high-quality sheets, towels, and spa toiletries for guest’s stay. Everything is stocked (TP, Paper Towels, Trash Bags, etc.). Guests are welcomed by a gift basket with hand-written card, Illy coffee, tea, Fiji water and more!
    pricing:
      bedbath: [Beds and Baths, 1 and 1, 2 and 1, 2 and 2, 3 and 2, 3 and 3] 
      type:
      - [Spotless Cleaning, '75.00', '95.00', '105.00', '120.00', '130.00']
      - [BNB Ready Package, '75.00', '80.00', '85.00', '90.00', '95.00']
    extras:
      popular: false
      animal: false
      recycle: false


  - spotlesscleaning: 
    product-id: 84194755
    title: Spotless Cleaning Service
    tag: We’ve got every room covered!
    feature-image: img-ser-spot-collage.jpg
    thumb-image: img-ser-spot-thumb.jpg
    link: service-spotless-cleaning.html
    excerpt: From top to bottom, ceiling fan to baseboards, we’ll have that baby sparkling in false time!  Betweenbnb believes in a Green and Animal Friendly world. That’s why we only use products that are green, organic, and animal friendly. Check out our arsenal!
    pricing:
      bedbath: [Beds and Baths, 1 and 1, 2 and 1, 2 and 2, 3 and 2, 3 and 3] 
      type:
      - [Spotless Cleaning, '75.00', '95.00', '105.00', '120.00', '130.00']
    extras:
      popular: false
      animal: false
      recycle: false


