
main:
  - hasslefree:
    product-id: 83701275
    title: Hassle-Free Hosting Service
    tag: You Won’t Lift a Finger
    price: 1,500
    feature-image: img-ser-hassle-collage.jpg
    thumb-image: img-ser-hassle-thumb.jpg
    link: service-hassle-free.html
    excerpt: 
    - Our Spotless Cleaning Service before AND after your guests come and go. We bring OUR OWN high-quality sheets, towels, and spa toiletries for guest’s stay. Everything is stocked (TP, Paper Towels, Trash Bags, etc.). Guests are welcomed by a gift basket with hand-written card, Illy coffee, tea, bottled water and more!
    - Basically, you collect the check and 5 Star Rating, we’ll do the rest!
    extras:
      popular: false
      animal: true
      recycle: true


  - spotlesscleaning: 
    product-id: 83644529
    title: Spotless Cleaning Service
    tag: We’ve got every room covered!
    price: 1,200
    feature-image: img-ser-spot-collage.jpg
    thumb-image: img-ser-spot-thumb.jpg
    link: service-spotless-cleaning.html
    excerpt: From top to bottom, ceiling fan to baseboards, we’ll have that baby sparkling in false time!  Betweenbnb believes in a Green and Animal Friendly world. That’s why we only use products that are green, organic, and animal friendly. Check out our arsenal!
    extras:
      popular: false
      animal: true
      recycle: true


