# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Betweenbnb
email: info@betweenbnb.com
emailProtect: info [at] betweenbnb.com
phone: (800) BNB-3317
phone_link: 8002623317

description: > # this means to ignore newlines until "baseurl:"
  Betweenbnb is a hospitality services company specializing in property preparation on behalf of Airbnb hosts before guests arrival and after guests departure. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://betweenbnb.com" # the base hostname & protocol for your site
assets: assets/img/


tw: http://www.twitter.com/betweenbnb
fb: http://facebook.com/betweenbnb
pn: http://pinterest.com/bbandbee
in: http://instagram.com/betweenbnb

# Build settings
markdown: kramdown

# Assets are being handled by Gulp
exclude: [assets]
keep_files: [assets]

# General 

cta_url: services.html
cta_header: Let's do this!
cta_page: Get Started


address:
  street: 21 Beacon Street Suite 4B
  city: Boston
  state: MA

# Store 11450045

store: 11499872

# Contact Form Elements
